### ISSUE TITLE
Compileing

### ISSUE THREAD

**Issue by polarbub** [handtruth/nbt-cpp#1]
I have 64bit g++ and I get errors when compiling

`e:/saves/code/c++/Mapart/include/nbt.hpp: In member function ‘auto nbt::tags::compound_tag::put(std::string&&, T&&)’:
e:/saves/code/c++/Mapart/include/nbt.hpp:838:17: error: ‘nbt::tags::compound_tag::value_type’ {aka ‘class std::map<std::basic_string<char>, std::unique_ptr<nbt::tags::tag> >’} has no member 
named ‘insert_or_assign’
  838 |    return value.insert_or_assign(std::move(name), std::make_unique<tag_of<T>>(std::move(item)));
      |                 ^~~~~~~~~~~~~~~~
e:/saves/code/c++/Mapart/include/nbt.hpp: In member function ‘auto nbt::tags::compound_tag::put(const string&, T&&)’:
e:/saves/code/c++/Mapart/include/nbt.hpp:843:17: error: ‘nbt::tags::compound_tag::value_type’ {aka ‘class std::map<std::basic_string<char>, std::unique_ptr<nbt::tags::tag> >’} has no member 
named ‘insert_or_assign’
  843 |    return value.insert_or_assign(name, std::make_unique<tag_of<T>>(item));
      |                 ^~~~~~~~~~~~~~~~`
      
   What does this mean / how do I fix it?

**Comment by Ktlo** [comment]
Can you provide your system environment details and steps to reproduce this error? I need OS name, GCC version, Meson and Ninja version numbers that was used to build it to examine it.

As I understand, the software was build using g++ directly without Meson or Ninja. In that case. It's possible, that you missed flag `-std=c++17`.

**Comment by polarbub** [comment]
Okay sorry about that. I am on win 10 64, gcc 10.2.0 through Cygwin 64.
Your fix worked but now I get more problems. 
`/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/Mapart.dir/Mapart.cpp.o:Mapart.cpp:(.data$_ZN3nbt4tags3endE[_ZN3nbt4tags3endE]+0x0): undefined reference to `vtable for nbt::tags::end_tag'     
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/Mapart.dir/Mapart.cpp.o:Mapart.cpp:(.data$_ZN3nbt4tags8end_listE[_ZN3nbt4tags8end_listE]+0x0): undefined reference to `vtable for nbt::tags::end_list_tag'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/Mapart.dir/Mapart.cpp.o:Mapart.cpp:(.rdata$.refptr._ZTVN3nbt4tags12end_list_tagE[.refptr._ZTVN3nbt4tags12end_list_tagE]+0x0): undefined reference to `vtable for nbt::tags::end_list_tag'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/Mapart.dir/Mapart.cpp.o:Mapart.cpp:(.rdata$.refptr._ZTVN3nbt4tags7end_tagE[.refptr._ZTVN3nbt4tags7end_tagE]+0x0): undefined reference to `vtable for nbt::tags::end_tag'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Mapart.dir/build.make:104: Mapart.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/Mapart.dir/all] Error 2
make: *** [Makefile:104: all] Error 2`

You can see the code here: https://github.com/Polarbub/Mapart-Program/tree/master
Also thank you for your help :)

**Comment by Ktlo** [comment]
There is a source file *src/nbt.cpp* that should be compiled independently and linked with your code. It uses *src/nbt_internal.hpp* header, that also should be added to your project. I didn't found them in your repository, so I assume this is the reason.
